/*
 * This file is generated by jOOQ.
*/
package com.spring3.demo.jooq;


import com.spring3.demo.jooq.tables.Author;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = com.spring3.demo.jooq.tables.Author.AUTHOR;
}
